/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { PrismaService } from "../../prisma/prisma.service";
import {
  Prisma,
  BackgroundSettings as PrismaBackgroundSettings,
} from "@prisma/client";

export class BackgroundSettingsServiceBase {
  constructor(protected readonly prisma: PrismaService) {}

  async count(
    args: Omit<Prisma.BackgroundSettingsCountArgs, "select">
  ): Promise<number> {
    return this.prisma.backgroundSettings.count(args);
  }

  async backgroundSettingsItems<
    T extends Prisma.BackgroundSettingsFindManyArgs
  >(
    args: Prisma.SelectSubset<T, Prisma.BackgroundSettingsFindManyArgs>
  ): Promise<PrismaBackgroundSettings[]> {
    return this.prisma.backgroundSettings.findMany<Prisma.BackgroundSettingsFindManyArgs>(
      args
    );
  }
  async backgroundSettings<T extends Prisma.BackgroundSettingsFindUniqueArgs>(
    args: Prisma.SelectSubset<T, Prisma.BackgroundSettingsFindUniqueArgs>
  ): Promise<PrismaBackgroundSettings | null> {
    return this.prisma.backgroundSettings.findUnique(args);
  }
  async createBackgroundSettings<T extends Prisma.BackgroundSettingsCreateArgs>(
    args: Prisma.SelectSubset<T, Prisma.BackgroundSettingsCreateArgs>
  ): Promise<PrismaBackgroundSettings> {
    return this.prisma.backgroundSettings.create<T>(args);
  }
  async updateBackgroundSettings<T extends Prisma.BackgroundSettingsUpdateArgs>(
    args: Prisma.SelectSubset<T, Prisma.BackgroundSettingsUpdateArgs>
  ): Promise<PrismaBackgroundSettings> {
    return this.prisma.backgroundSettings.update<T>(args);
  }
  async deleteBackgroundSettings<T extends Prisma.BackgroundSettingsDeleteArgs>(
    args: Prisma.SelectSubset<T, Prisma.BackgroundSettingsDeleteArgs>
  ): Promise<PrismaBackgroundSettings> {
    return this.prisma.backgroundSettings.delete(args);
  }
}
